[package]
name = "notary-server"
version = "0.1.0-alpha.6"
edition = "2021"

[dependencies]
tlsn-common = { workspace = true }
tlsn-verifier = { workspace = true }

async-trait = { workspace = true }
async-tungstenite = { workspace = true, features = ["tokio-native-tls"] }
axum = { workspace = true, features = ["ws"] }
axum-core = { version = "0.4" }
axum-macros = { version = "0.4" }
base64 = { version = "0.21" }
chrono = { version = "0.4" }
csv = { version = "1.3" }
eyre = { version = "0.6" }
futures = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["client", "http1", "server"] }
hyper-util = { workspace = true, features = ["full"] }
notify = { version = "6.1.1", default-features = false, features = [
    "macos_kqueue",
] }
p256 = { workspace = true }
rustls = { version = "0.23" }
rustls-pemfile = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { version = "0.9" }
sha1 = { version = "0.10" }
structopt = { version = "0.3" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-rustls = { workspace = true }
tokio-util = { workspace = true, features = ["compat"] }
tower = { version = "0.4", features = ["make"] }
tower-http = { version = "0.5", features = ["cors"] }
tower-service = { version = "0.3" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
uuid = { workspace = true, features = ["v4", "fast-rng"] }
ws_stream_tungstenite = { workspace = true, features = ["tokio_io"] }
tokio-rustls-acme = "=0.4.0"
clap = { version = "4", features = ["derive"] }
log = "0.4.17"
simple_logger = "4.1"
tokio-stream = { version="0.1.9", features = ["net"] }



